# 各パッケージの用途と、拡張を Profile へ振り分ける手順は
# dotfiles/docs/settings.md「Brewfile」を参照
tap "hashicorp/tap"

brew "gh"
brew "postgresql@18"
brew "node"
brew "openjdk@21"
brew "rbenv"
brew "yarn"
brew "hashicorp/tap/terraform"
brew "herdr"

cask "claude-code"
cask "ghostty"

vscode "anthropic.claude-code"
vscode "castwide.solargraph"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-rename-tag"
vscode "hashicorp.terraform"
vscode "hediet.vscode-drawio"
vscode "hridoy.rails-snippets"
vscode "ionutvmi.path-autocomplete"
vscode "kaiwood.endwise"
vscode "misogi.ruby-rubocop"
vscode "ms-ceintl.vscode-language-pack-ja"
vscode "ms-vscode.live-server"
vscode "ms-vsliveshare.vsliveshare"
vscode "oderwat.indent-rainbow"
vscode "pkief.material-icon-theme"
vscode "qwtel.sqlite-viewer"
vscode "repreng.csv"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "shopify.ruby-lsp"
vscode "streetsidesoftware.code-spell-checker"
vscode "whizkydee.material-palenight-theme"
vscode "yzhang.markdown-all-in-one"
